name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      # Esto lo comento porque esta variable de ambiente se define en el config.ini
      # - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
    # Nota mental: esto es siempre un absolute path. No asume por defecto PWD, tenes que pasar el .
      - ./server/config.ini:/config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - NOMBRE=MATIAS
      - APELLIDO=PEREZ
      - DOCUMENTO=12345678
      - NACIMIENTO=2009-12-14
      - NUMERO=1234
      # Ditto LOGGING_LEVEL
      # - CLI_LOG_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - ./client/config.yaml:/config.yaml

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

